### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ilobilo** [Killaship/Codename-Spectrum#5]
1) Don't put everything in one file
2) Do not register every isr and irq manually, create function that does it for you
Something like this: https://github.com/ilobilo/kernel/blob/b7a8262f65a4da5429ade4471b3da5f8e131faa3/source/system/idt/idt.cpp#L7

**Comment by Killaship** [comment]
Ok, if I'm using #includes, do I have to link the files i'm including, or does gcc do it for me?

**Comment by ilobilo** [comment]
Use Makefile:
https://github.com/ilobilo/kernel/blob/master/Makefile

**Comment by ilobilo** [comment]
Sorry different file:
https://github.com/ilobilo/kernel/blob/master/source/Makefile

**Comment by Killaship** [comment]
ok. Closing issue. aaaaaaaaaaaaaa
